### ISSUE TITLE
Download 

### ISSUE THREAD

**Issue by Jkurbs** [cs-chan/ArtGAN#5]
Hi I'm trying to download the file with Wget or Aria2. Is there any direct link that I can use to download it?

**Comment by willtwr** [comment]
Hi,

I assume that you are referring to the dataset.
Currently, we do not have and plan to create a direct link for the dataset.

However, you should still be able to download the dataset with wget.
As far as I know, you need to modify the address in order to make wget works on downloading large files from google drive. 
As for how to do it, I am sorry to tell you that I don't remember and I am afraid that you have to google it. 

Best,
William

**Comment by Jkurbs** [comment]
Hi, I still can't find a way to download it fast, even with wget. Could you suggest me any other solution? 

Thank you very much!

**Comment by cs-chan** [comment]
HI, we have updated the link. Can you try again, please? Thank you.

**Comment by tony0902** [comment]
Hi,@cs-chan.
Your link is broken. Can you update again,please?

**Comment by cs-chan** [comment]
Hi Tony,

May I know which link,please? 

With best wishes,
Chan

**Comment by tony0902** [comment]
I just tried it and it works now!
thank you very much!
